---
# tasks file for deploy_db_postgresql
- name: Install PostgreSQL
  apt:
    pkg:
      - postgresql
      - postgresql-contrib
      - postgresql-server-dev-all
      - python3-psycopg2
#      - python-psycopg2
      - libpq-dev
    state: latest
    update_cache: yes
  become: true
  
- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  
- name: install psycopg2
  pip:
    name: psycopg2
  become: true
  
- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres
  become: yes

- name: Create DB user
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres 

# parameters for my DB user - myprojectuser
  
- name: Set default encoding for db user
  become: true
  become_user: postgres
  command: psql -U postgres -c "ALTER ROLE {{ db_user }} SET client_encoding TO 'utf8'"

- name: Set default transaction isolation for db user
  become: true
  become_user: postgres
  command: psql -U postgres -c "ALTER ROLE {{ db_user }} SET default_transaction_isolation TO 'read committed'"

- name: Set default timezone for db user
  become: true
  become_user: postgres
  command: psql -U postgres -c "ALTER ROLE {{ db_user }} SET timezone TO 'UTC'"

#- name: Grant ALL PRIVILEGES to myprojectuser on myproject DB
#  become: true
#  become_user: postgres
#  command: psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }}"

