---
# tasks file for deploy_gunicorn
- name: Install Gunicorn
  pip:
     name: gunicorn
     virtualenv: "{{project_name_path}}/myprojectenv"
     virtualenv_command: virtualenv
     virtualenv_python: python3
  become: true

- name: Create Gunicorn Socket file
  template: src=gunicorn.socket.j2 dest=/etc/systemd/system/gunicorn.socket
  become: true
  
- name: Create Gunicorn Service file
  template: src=gunicorn.service.j2 dest=/etc/systemd/system/gunicorn.service 
  become: true
  
- name: Start Gunicorn.socket
  shell: "/bin/systemctl start gunicorn.socket"
  become: true
  
- name: Enable Gunicorn.socket
  shell: "/bin/systemctl enable gunicorn.socket"
  become: true
