---
# tasks file for server_prepare
- name: Run apt-get update
  become: true
  apt:
    update_cache: yes

- name: Install base packages for python3 env
  apt:
    pkg:
    - python3
    - python3-pip
    - python3-dev
    - python3-virtualenv
    - virtualenv
    state: latest

#- name: Set env for default python3
#  shell: "sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 3"
